# -*- coding: utf-8 -*-
"""Q1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PHDPpi-9avE9PsfIAe8tQonrWbniehSw

Q1.Develop a program to read a four-digit number and find its

a. Sum of digits

b. Reverse

c. Difference between the product of digits at the odd position 
and the product of digits at the even position.
"""

n=int(input('Enter a 4-digit number = '))
dig1=n%10
dig2=(n//10)%10
dig3=(n//100)%10
dig4=(n//1000)%10
sum=dig1+dig2+dig3+dig4
print('Sum : ',sum)
print('Reverse : ',(dig1*1000)+(dig2*100)+(dig3*10)+dig4)
print((dig4*dig2)-(dig3*dig1))