# -*- coding: utf-8 -*-
"""Lab3q2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CsQBb3kgkdmjKYMfBUwsWt6_iLCF-TaZ
"""

from numpy import array
from numpy import mean
from numpy import cov
from numpy.linalg import eig

def computePCA():

  n, m = map(int, input("Enter number of rows and column : ").split()) 
  A = array([input("Enter elements row by row : ").strip().split() for _ in range(n)], int)
  print(A)
  M = mean(A, axis=0)
  C = A - M
  V = cov(C.T)
  values, vectors = eig(V)
  projection_matrix = (vectors.T[:][:2]).T
  P = projection_matrix.T.dot(C.T)
  print(P.T)

computePCA()