# -*- coding: utf-8 -*-
"""Q3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gJ91wurKT-JZz4AoHoBW3Vtan06y5WUJ

Q1.Develop a program to read the employee's name, code, and basic pay 
and calculate the gross salary, deduction, and net salary according to 
the following conditions. Define a function to find each of the 
components. Finally, generate a payslip.
"""

name=input('Enter your name : ')
code=int(input('Enter the code : '))
BP=int(input('Enter your basic pay : '))

if(BP<10000):
  DA=(5/100)*BP
  HRA=(2.5/100)*BP
  MA=500
  PT=20
  PF=(8/100)*BP
  IT=0
elif(BP<30000):
  DA=(7.5/100)*BP
  HRA=(5/100)*BP
  MA=2500
  PT=60
  PF=(8/100)*BP
  IT=0
elif(BP<50000):
  DA=(11/100)*BP
  HRA=(7.5/100)*BP
  MA=5000
  PT=60
  PF=(11/100)*BP
  IT=(11/100)*BP
else:
  DA=(25/100)*BP
  HRA=(11/100)*BP
  MA=7000
  PT=80
  PF=(12/100)*BP
  IT=(20/100)*BP

def gross_salary():
  GS=BP+DA+HRA+MA
  return(GS)

def deduction_amount():
  D=PT+PF+IT
  return(D)

def net_salary():
  netsalary=(gross_salary()-deduction_amount())
  return(netsalary)

print('Payslip')
print('Name : ',name)
print('Code : ',code)
print('Basic pay : ',BP)
print('Gross salary : ',gross_salary())
print('Deduction : ',deduction_amount())
print('Net Salary : ',net_salary())