# -*- coding: utf-8 -*-
"""Q5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vkLGkZFqC-UU_TkgpJzlsqnzmrXrWrWC

5. Develop a program to read a string and perform the following 
operations:

• Print all possible substrings.

• Print all possible substrings of length K.

• Print all possible substrings of length K with N distinct 
characters.

• Print substring(s) of length maximum length with N distinct 
characters.

• Print all palindrome substrings
"""

def sub_string(s):
  l=len(s)
  print('Possible substrings : ')
  for i in range(0,l+1):
    for j in range(i+1,l+1):
      print(s[i:j])

s=input('Enter the string :')
sub_string(s)

def length_k(s,k):
  l=len(s)
  for i in range(0,l+1):
    for j in range(i+1,l+1):
      if len(s[i:j])==k:
        print(s[i:j])
k=int(input('Enter length : '))
length_k(s,k)

def distinct(s,k):
  l=len(s)
  print('Distinct substring : ')
  for i in range(0,l+1):
    for j in range(i+1,l+1):
      substring=s[i:j]
      sett=set(substring)
      if len(substring)==k:
        if len(sett)==k:
          print(substring)
distinct(s,k)

def palindrome():
  slic=s[::-1]
  if(slic==s):
    print('Palindrome : ',slic)
  else:
    print('Not palindrome : ',slic)
palindrome()