# -*- coding: utf-8 -*-
"""Q2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fwsqOlLCsrwglVkcFofW9XMpYw3HZ3VP

Q2.Develop a program to read the three sides of two triangles and 
calculate the area of both. Define a function to read the three sides 
and call it. Also, define a function to calculate the area. Print the total 
area enclosed by both triangles and each triangle's contribution (%) 
towards it
"""

import math

def read_sides():
  a=int(input('Enter side 1 : '))
  b=int(input('Enter side 2 : '))
  c=int(input('Enter side 3 : '))
  return(a,b,c)

def get_area(a,b,c):
  s=(a+b+c)/2
  area=math.sqrt(s*(s-a)*(s-b)*(s-c))
  return(area)

print('Area of triangle 1 : ')
a,b,c = read_sides()
print(get_area(a,b,c))
  
print('Area of triangle 2 : ')
x,y,z=read_sides()
print(get_area(x,y,z))

total=get_area(a,b,c)+get_area(x,y,z)
print('Total Area : ',total)

print('Contribution to area of triangle 1 : ',(get_area(a,b,c)/total)*100)
print('Contribution of area of traingle 2 : ',(get_area(x,y,z)/total)*100)