# -*- coding: utf-8 -*-
"""Lab2Q5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lLumHjGyC3-27zxO_hEfch-6Lk4Tih33

Q5.Write a program to create a parent class, 3DShapes, with methods printVolume() and printArea(), which prints the Volume and Area, respectively. Create classes Cylinder and Sphere by inheriting 3DShapes class. Using these child classes, calculate and print the volume and area of a cylinder and sphere.
"""

class threeD_Shapes:
  def printVolume(show):
    print("Volume is ",show.volume)
  def printArea(show):
    print("Area is ",show.area)
  
#derived class for calculation of area and volume of cylinder
class cylinder(threeD_Shapes):

  def __init__(show,r,h):
    show.radius = r
    show.height = h
  def calc_area(show):
    show.area = 2*3.14*show.radius*(show.radius+show.height)
  def calc_volume(show):
    show.volume = round((3.14*show.radius*show.radius*show.height),2)

#derived class for calculation of area and volume of sphere
class sphere(threeD_Shapes):
    def __init__(show,r):
      show.radius = r
    def calc_area(show):
      show.area = 4*3.14*show.radius*show.radius
    def calc_volume(show):
      show.volume = round(((4/3)*3.14*(show.radius**3)),2)

cylinder_r = int(input("Enter the radius of the cylinder : "))
cylinder_h = int(input("Enter the height of the cylinder : "))
cylinder_obj = cylinder(cylinder_r,cylinder_h)
cylinder_obj.calc_area()
cylinder_obj.printArea()
cylinder_obj.calc_volume()
cylinder_obj.printVolume()

sphere_r = int(input("\nEnter the radius of the sphere : "))
sphere_obj = sphere(sphere_r)
sphere_obj.calc_area()
sphere_obj.calc_volume()
sphere_obj.printArea()
sphere_obj.printVolume()